### ISSUE TITLE
signed tag for a release

### ISSUE THREAD

**Issue by eighthave** [signalapp/gradle-witness#8]
I'd like to package this and include it in Debian.  It would be best if there was an official "release" for gradle-witness that can then be packaged.  That's trivial to do with github.com: just make a signed tag that marks the version, and push it to this repo.  The Debian packaging can then get the source tarball from github directly.

**Comment by moxie0** [comment]
I'm working on uninstalling gpg. I don't think packaging for debian makes sense, since it needs to be installed per-project to make it portable gradle.
